# Generated by Django 3.1.5 on 2021-06-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(max_length=64, verbose_name='Название категории')),
                ('url', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProductLine', models.CharField(max_length=64, verbose_name='Название линейки(коллекции)')),
                ('aboutProductLine', models.TextField(blank=True, verbose_name='О линейке')),
                ('photoProductLine', models.ImageField(upload_to='images/lines/%Y/%m/%d/', verbose_name='Логотип линейки')),
            ],
            options={
                'verbose_name': 'Линейка',
                'verbose_name_plural': 'Линейки',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSection', models.CharField(max_length=64, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=64, verbose_name='Никнейм юзера')),
                ('photoUser', models.ImageField(blank=True, upload_to='images/users/%Y/%m/%d/', verbose_name='Фото юзера')),
                ('emailUser', models.EmailField(max_length=64, verbose_name='Email юзера')),
                ('passwordUser', models.CharField(max_length=64, verbose_name='Пароль юзера')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(max_length=64, verbose_name='Наименование продукта')),
                ('photoProduct', models.ImageField(blank=True, upload_to='images/products/%Y/%m/%d/', verbose_name='Фото одежды')),
                ('priceProduct', models.PositiveIntegerField(help_text='руб.', verbose_name='Цена продукта')),
                ('quantityProduct', models.PositiveSmallIntegerField(help_text='на складе', verbose_name='Количество на складе')),
                ('materialProduct', models.CharField(max_length=128, verbose_name='Материал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория одежды')),
                ('productLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productline', verbose_name='Линейка')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.section', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countProduct', models.PositiveSmallIntegerField(help_text='руб.', verbose_name='Цена продукта')),
                ('summPrice', models.PositiveIntegerField(help_text='руб.', verbose_name='Цена зв ед.продукта')),
                ('promocode', models.CharField(max_length=8, verbose_name='Промокод')),
                ('totalPrice', models.PositiveIntegerField(help_text='руб.', verbose_name='Итоговая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Категория одежды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user', verbose_name='Категория одежды')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
