# Generated by Django 3.1.5 on 2021-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210605_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productline',
            options={'verbose_name': 'Линейку', 'verbose_name_plural': 'Линейки'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='countProduct',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='summPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='sizesProduct',
            field=models.ManyToManyField(to='shop.Sizes', verbose_name='Доступные размеры'),
        ),
        migrations.AddField(
            model_name='section',
            name='shortName',
            field=models.CharField(default='U', max_length=1, verbose_name='Аббревиатура раздела'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='shop.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photoProduct',
            field=models.ImageField(blank=True, upload_to='images/products/', verbose_name='Фото товара'),
        ),
    ]
