# Generated by Django 3.1.5 on 2021-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210605_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promocode',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.FloatField(default=0, max_length=4, verbose_name='Скидка на товар'),
        ),
        migrations.AlterField(
            model_name='section',
            name='shortName',
            field=models.CharField(max_length=3, verbose_name='Аббревиатура раздела'),
        ),
    ]
