# Generated by Django 3.1.5 on 2021-01-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210123_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя товара')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Логотип компании')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория одежды')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company', verbose_name='Компания производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
