# Generated by Django 3.1.5 on 2021-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=1, max_length=255, verbose_name='Страна производитель'),
            preserve_default=False,
        ),
    ]
