# Generated by Django 3.1.5 on 2021-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210606_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='urlProductLine',
            field=models.SlugField(default='url', max_length=12),
            preserve_default=False,
        ),
    ]
