# Generated by Django 3.1.5 on 2021-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productline_urlproductline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='urlProductLine',
            field=models.SlugField(max_length=12, unique=True),
        ),
    ]
