# Generated by Django 3.1.5 on 2021-02-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_company_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Линейка', 'verbose_name_plural': 'Линейки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AlterField(
            model_name='company',
            name='aboutCompany',
            field=models.TextField(blank=True, verbose_name='О линейке'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Логотип линейки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название линейки(коллекции)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company', verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Наименование продукта'),
        ),
    ]
