# Generated by Django 3.1.5 on 2021-06-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210609_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар для корзины', 'verbose_name_plural': 'Товары для корзины'},
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='sizesProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.sizes', verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.PositiveIntegerField(default=0, help_text='руб.', verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
