# Generated by Django 3.1.5 on 2021-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210609_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='sizesProduct',
            field=models.CharField(default='', max_length=2, verbose_name='размер'),
        ),
    ]
