# Generated by Django 3.1.5 on 2021-06-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210609_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='sizesProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sizes', verbose_name='размер'),
        ),
    ]
