# Generated by Django 3.1.5 on 2021-06-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_auto_20210609_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='руб.', max_digits=9, verbose_name='Итоговая цена'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('country_choices', models.CharField(choices=[('russia', 'Россия'), ('ukraine', 'Украина'), ('belarus', 'Беларусь'), ('kazakhstan', 'Казахстан')], default='russia', max_length=64, verbose_name='Страна')),
                ('region', models.CharField(default='Московская область', max_length=64, verbose_name='Область')),
                ('locality', models.CharField(default='Москва', max_length=64, verbose_name='Город/Поселок')),
                ('postcode', models.IntegerField(default=0, max_length=6, verbose_name='Почтовый код')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Адрес')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
