# Generated by Django 3.1.5 on 2021-06-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210614_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.IntegerField(default=0, verbose_name='Почтовый код'),
        ),
    ]
