# Generated by Django 3.1.5 on 2021-06-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='руб.', max_digits=9, verbose_name='Цена заказа'),
        ),
    ]
