# Generated by Django 3.1.5 on 2021-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.AlterField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='Корзина готова'),
        ),
    ]
